### ISSUE TITLE
Docker file only works for ros_distros target at ubuntu 20.04

### ISSUE THREAD

**Issue by caioaamaral** [orise-robotics/ros2-docker-devel#12]
I'll close #11 and #9 so we can track everything here (the root problem)

**Comment by caioaamaral** [comment]
For **dashing** and **melodic** the ./build_image is working without errors, but when trying to start the containter it will fail:
```
./run-devel.sh -d dashing
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

**kinetic** will fail during image building:

```
Step 5/24 : RUN echo 'Etc/UTC' > /etc/timezone &&     ln -s /usr/share/zoneinfo/Etc/UTC /etc/localtime &&     apt-get update &&     apt-get install -q -y --no-install-recommends tzdata &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 9dac09e21404
ln: failed to create symbolic link '/etc/localtime': File exists
```

**Comment by ivan1993br** [comment]
Considering docker not working between distro, I had a problem running 20.04 on ubuntu 18.04 due to our shared workspace, the main problem is [here](http://0pointer.net/blog/dynamic-users-with-systemd.html), with dynamic user kernel feature usage on systemd

**Comment by ivan1993br** [comment]
I set urgent-fix here because any user from ubuntu < 19 that comes to this package will not be able to run it directly, and this will definitely cut a lot of users

**Comment by caioaamaral** [comment]
@ivan1993br could you please test again using #24 and check if your problem persist or not?
