### ISSUE TITLE
Error on installing `git-lfs`

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/ros2-docker-devel#49]
When I install `git-lfs`, I get the following error:
```
dpkg: error processing package git-lfs (--configure):
 installed git-lfs package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 git-lfs
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I think the [gitconfig](https://github.com/orise-robotics/ros_ws/blob/4c974fe3c3b993b4bd03ce385845503cda2b1e82/docker-compose.yml#L20) binding in the root environment is related to this problem. I suggest binding with the file from the user folder.

**Comment by caioaamaral** [comment]
I'm not sure but I think something had changed on docker API. I think we have a new behavior for how it sets the user id. Maybe we don't even need to use gosu anymore.

Perhaps this change is causing the git-lfs error somehow...

**Comment by mateus-amarante** [comment]
I think it would be good to remove the gosu stuff with the intent of simplifying it if possible.
