### ISSUE TITLE
Use hardware acceleration on the container

### ISSUE THREAD

**Issue by ivan1993br** [orise-robotics/ros2-docker-devel#5]
Allow the usage of hardware acceleration for complex tests and simulation

**Comment by mateus-amarante** [comment]
Could you provide any reference for what you call "graphic boards"?

**Comment by ivan1993br** [comment]
> Could you provide any reference for what you call "graphic boards"?

"Graphic board" is not the correct naming, my mistake, is graphic cards, like nvidia.

**Comment by mateus-amarante** [comment]
@ivan1993br, are you working on this? I think we need this to run rviz2

**Comment by ivan1993br** [comment]
Actually, I was not, did you fix it?
