### ISSUE TITLE
Why do we need gosu? Can we remove it?

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/ros2-docker-devel#60]
I'm willing to clean up the container, and I think `gosu` isn't required. Am I right @caioaamaral?

**Comment by caioaamaral** [comment]
> I'm willing to clean up the container, and I think `gosu` isn't required. Am I right @caioaamaral?

I think it's completely replaceable, but I didn't test removing it. 

The only problem I think we might face (**and I'm not even sure if gosu is actually solving it**) are directories that are generated during docker build having the wrong user permission. Setting up the right user before creating such directories should be enough (IIRC that was the reason we moved with gosu at first place)

**Comment by mateus-amarante** [comment]
Today, files created in the home folder during the build step disappear because we mount a volume there. Files outside this folder usually are owned by root. Therefore, I couldn't identify any problem with user permissions.
