### ISSUE TITLE
Relax workspace volume definition, making a docker volume by default

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/ros2-docker-devel#61]
Today, the `run-devel.sh` script defines a `VOLUME_FOLDER` to set the host folder to bind the persistent workspace volume. I suggest we define it as a named volume based on the container name and add an option to the user to define as desired.

**Comment by caioaamaral** [comment]
That never occurred to me, I think that approach is actually better than using a folder in the host $HOME
