### ISSUE TITLE
Organize files

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/ros2-docker-devel#67]
I suggest some file organization changes:
- Make `devel` and `test` entrypoint filenames symmetric
- Move the entry point files to a separate folder(?)
- Move Dockerfiles to a dedicated folder(?)
- Rename `.env` file to something more intuitive (`env.sh` or `.config`)

**Comment by caioaamaral** [comment]
> * Move the entry point files to a separate folder(?)

Since we are copying them into the container, we could create a rootfs folder (and just copy the folder itself)

> Rename .env file to something more intuitive (env.sh or .config)

I like `.settings`, IMO the shell suffix is dispensable

**Comment by mateus-amarante** [comment]
Actually, the `.sh` proposal invokes another idea I have of letting it be a bash script to have more flexibility on setting the environment variables. `docker-compose`'s `.env` file is limited (for example, I cannot reuse a variable name to define other variables)
