### ISSUE TITLE
Discussion about styles and standards

### ISSUE THREAD

**Issue by mateus-amarante** [orise-robotics/ros2-docker-devel#8]
I am opening this issue to discuss styles and standards. This topic was raised in https://github.com/open-br/diffbot2_robot/pull/2#discussion_r506760565 and I think it is very relevant.

As a baseline rule, I think we should stick to the [REP](https://ros.org/reps/rep-0000.html) standards and the most commonly used styles for ROS2 packages.

**Comment by mateus-amarante** [comment]
By the way, I would like to reference [REP 2004 - Package Quality Categories](https://ros.org/reps/rep-2004.html). I think this is a core REP to inspire on.

**Comment by ivan1993br** [comment]
Wow, you goal I just checked the link, what do you think, we can set a quality goal?

**Comment by mateus-amarante** [comment]
I would say at least Level 3
